### ISSUE TITLE
Buttons hidden in night mode

### ISSUE THREAD

**Issue by tonygambone** [caman9119/SpaceLaunchNow#34]
The buttons on the launch list ("Watch Live", "Explore", "Share") are hidden when Night Mode is on:

First with Night Mode off:

![screenshot_2016-03-08-07-07-39](https://cloud.githubusercontent.com/assets/44966/13601822/cf1e9bc2-e500-11e5-895c-44bb60a027e2.png)

Then after turning on Night Mode:

![screenshot_2016-03-08-07-07-11](https://cloud.githubusercontent.com/assets/44966/13601823/d0f4afae-e500-11e5-9988-8592932574f6.png)

This is on a Galaxy S6, Android 5.1.1.

Love this app BTW, I'm a bit of a junkie and had been wishing for something like this for quite a while!

**Comment by caman9119** [comment]
Thanks Tony, already got a fix for this in the next release. Waiting on Google to provide a fix for this: https://code.google.com/p/android/issues/detail?id=201817

**Comment by tonygambone** [comment]
Got the update & looks good now, thanks!

**Comment by caman9119** [comment]
Awesome, thanks.
