### ISSUE TITLE
Submit to F-Droid

### ISSUE THREAD

**Issue by glitchphan** [caman9119/SpaceLaunchNow#51]
There is nothing like this app in F-Droid open source market (http://f-droid.org).

**Comment by caman9119** [comment]
I've been trying to get this app on F-Droid, got locked out of my account. Still working on it.

**Comment by caman9119** [comment]
Got logged in and submitted for approval, still waiting.

**Comment by glitchphan** [comment]
Did it never get approved or something?

**Comment by caman9119** [comment]
Still has not been approved, i'm tracking it on the [Trello](https://trello.com/b/DwLCfv7g/space-launch-now) roadmap though.
