### ISSUE TITLE
Request: Filter Launches with Livestreams Only

### ISSUE THREAD

**Issue by tariq86** [caman9119/SpaceLaunchNow#54]
As the title says, add an option to filter visible space launches (and their alerts/notifications) to those that have livestreams only.

**Comment by caman9119** [comment]
That seems doable. Thanks for the suggestion.

**Comment by tariq86** [comment]
Do you accept pull requests? If so, I can take care of this

**Comment by caman9119** [comment]
I do, i've already added it in the latest Beta release though. =p
