### ISSUE TITLE
Bug: Next Launch not loading on Wear Watch face

### ISSUE THREAD

**Issue by Immabed** [caman9119/SpaceLaunchNow#64]
Device: Moto 360 (wear 1.4, android 6.0.1, Nexus 5 on 6.0.1 connected)
Bug: On the watch face, the next launch indicator never loads, continuously shows "Syncing Next Launch..."

Edit: SLN version 1.4.2

**Comment by caman9119** [comment]
Fixed for good in the latest Alpha build #68
